export const languages = [
    { id: 'en', name: 'English', flag: '🇬🇧' },
    { id: 'de', name: 'Deutsch', flag: '🇩🇪' }
];

export const levels = ['B1', 'B2', 'C1'];

// --- ENGLISH CONTENT ---
const enB1Words = [
    { word: 'Appointment', translation: 'Cita', example: 'I have an appointment at 3 PM.' },
    { word: 'Deadline', translation: 'Fecha límite', example: 'The deadline for the project is tomorrow.' },
    { word: 'Colleague', translation: 'Colega', example: 'My colleague is very helpful.' },
    { word: 'Feedback', translation: 'Comentarios', example: 'I need feedback on my presentation.' },
    { word: 'Schedule', translation: 'Horario', example: 'Let me check my schedule.' },
    { word: 'Promotion', translation: 'Ascenso', example: 'She got a promotion last month.' },
    { word: 'Client', translation: 'Cliente', example: 'The client is coming at noon.' },
    { word: 'Meeting', translation: 'Reunión', example: 'The meeting lasted two hours.' },
    { word: 'Overtime', translation: 'Horas extras', example: 'I worked overtime last week.' },
    { word: 'Salary', translation: 'Salario', example: 'The salary is paid monthly.' },
    { word: 'Bonus', translation: 'Bono', example: 'He received a performance bonus.' },
    { word: 'Training', translation: 'Entrenamiento', example: 'We have a training session today.' },
    { word: 'Contract', translation: 'Contrato', example: 'Sign the contract here.' },
    { word: 'Department', translation: 'Departamento', example: 'Which department do you work in?' },
    { word: 'Manager', translation: 'Gerente', example: 'Talk to the manager about it.' }
];

const enB2Words = [
    { word: 'Sustainability', translation: 'Sostenibilidad', example: 'Focus on environmental sustainability.' },
    { word: 'Pollution', translation: 'Contaminación', example: 'Air pollution is a major problem.' },
    { word: 'Renewable', translation: 'Renovable', example: 'Solar energy is renewable.' },
    { word: 'Biodiversity', translation: 'Biodiversidad', example: 'Protecting biodiversity is crucial.' },
    { word: 'Conservation', translation: 'Conservación', example: 'Wildlife conservation is vital.' },
    { word: 'Climate change', translation: 'Cambio climático', example: 'Climate change affects everyone.' },
    { word: 'Ecosystem', translation: 'Ecosistema', example: 'Don\'t disrupt the ecosystem.' },
    { word: 'Recycling', translation: 'Reciclaje', example: 'Recycling reduces waste.' },
    { word: 'Atmosphere', translation: 'Atmósfera', example: 'The atmosphere protects the Earth.' },
    { word: 'Environment', translation: 'Medio Ambiente', example: 'We must protect the environment.' },
    { word: 'Deforestation', translation: 'Deforestación', example: 'Deforestation leads to habitat loss.' },
    { word: 'Emission', translation: 'Emisión', example: 'Carbon emissions are increasing.' },
    { word: 'Habitat', translation: 'Hábitat', example: 'Many animals are losing their habitat.' },
    { word: 'Preserve', translation: 'Preservar', example: 'We should preserve natural resources.' },
    { word: 'Regulation', translation: 'Regulación', example: 'New environmental regulations are in place.' },
    { word: 'Impact', translation: 'Impacto', example: 'The impact on the environment is severe.' },
    { word: 'Resource', translation: 'Recurso', example: 'Water is a precious resource.' },
    { word: 'Hazardous', translation: 'Peligroso', example: 'Properly dispose of hazardous waste.' },
    { word: 'Infrastructure', translation: 'Infraestructura', example: 'Better cycling infrastructure is needed.' },
    { word: 'Alternative', translation: 'Alternativa', example: 'Wind power is an alternative energy source.' },
    { word: 'Consumption', translation: 'Consumo', example: 'Energy consumption is at its peak.' },
    { word: 'Efficient', translation: 'Eficiente', example: 'LED bulbs are more energy efficient.' },
    { word: 'Organic', translation: 'Orgánico', example: 'I prefer buying organic produce.' },
    { word: 'Erosion', translation: 'Erosión', example: 'Soil erosion is a common problem.' },
    { word: 'Greenhouse', translation: 'Invernadero', example: 'The greenhouse effect warms the planet.' },
    { word: 'Solar power', translation: 'Energía solar', example: 'Solar power is becoming cheaper.' },
    { word: 'Wind turbine', translation: 'Turbina eólica', example: 'The wind turbine generates electricity.' },
    { word: 'Ozone layer', translation: 'Capa de ozono', example: 'The ozone layer is healing.' },
    { word: 'Wildlife', translation: 'Vida silvestre', example: 'The park is home to diverse wildlife.' },
    { word: 'Marine', translation: 'Marino', example: 'Marine pollution affects oceans.' }
];

const enC1Words = [
    { word: 'Furthermore', translation: 'Además', example: 'Furthermore, the evidence is clear.' },
    { word: 'Ambiguous', translation: 'Ambiguo', example: 'The results are quite ambiguous.' },
    { word: 'Pragmatic', translation: 'Pragmático', example: 'Take a pragmatic approach to the issue.' },
    { word: 'Cognitive', translation: 'Cognitivo', example: 'Cognitive development is interesting.' },
    { word: 'Hypothesize', translation: 'Hipotetizar', example: 'Researchers hypothesize a link.' },
    { word: 'Synthesize', translation: 'Sintetizar', example: 'Synthesize the findings into a report.' },
    { word: 'Nuance', translation: 'Matiz', example: 'Pay attention to the nuance in his speech.' },
    { word: 'Paradigm', translation: 'Paradigma', example: 'We need a new paradigm for solving this.' },
    { word: 'Altruism', translation: 'Altruismo', example: 'Pure altruism is rare in humans.' },
    { word: 'Determinism', translation: 'Determinismo', example: 'The debate over free will and determinism.' },
    { word: 'Epistemology', translation: 'Epistemología', example: 'Epistemology studies the nature of knowledge.' },
    { word: 'Intrinsic', translation: 'Intrínseco', example: 'Kindness has an intrinsic value.' },
    { word: 'Subjective', translation: 'Subjetivo', example: 'Art is purely subjective.' },
    { word: 'Morality', translation: 'Moralidad', example: 'Objective morality is a complex topic.' },
    { word: 'Rationalize', translation: 'Racionalizar', example: 'Don\'t rationalize your mistakes.' },
    { word: 'Virtue', translation: 'Virtud', example: 'Patience is a great virtue.' },
    { word: 'Exacerbate', translation: 'Exacerbar', example: 'The new laws might exacerbate the problem.' },
    { word: 'Infrastructure', translation: 'Infraestructura', example: 'The city needs better infrastructure.' },
    { word: 'Globalisation', translation: 'Globalización', example: 'Globalisation affects small businesses.' },
    { word: 'Inequality', translation: 'Inequidad', example: 'Wealth inequality is at an all-time high.' },
    { word: 'Sustainability', translation: 'Sostenibilidad', example: 'Economic sustainability is a priority.' },
    { word: 'Autonomy', translation: 'Autonomía', example: 'Students need autonomy in their learning.' },
    { word: 'Benevolence', translation: 'Benevolencia', example: 'He was known for his benevolence.' },
    { word: 'Conundrum', translation: 'Acertijo/Dilema', example: 'It is a complex ethical conundrum.' },
    { word: 'Dichotomy', translation: 'Dicotomía', example: 'The dichotomy between good and evil.' },
    { word: 'Ephemeral', translation: 'Efímero', example: 'Fame is often ephemeral.' },
    { word: 'Garrulous', translation: 'Locuaz', example: 'The garrulous neighbor kept talking.' },
    { word: 'Inscrutable', translation: 'Inescrutable', example: 'His expression remained inscrutable.' },
    { word: 'Loquacious', translation: 'Loquaz', example: 'The loquacious presenter was very engaging.' },
    { word: 'Meticulous', translation: 'Meticuloso', example: 'She is meticulous about her work.' },
    { word: 'Nebulous', translation: 'Nebuloso', example: 'The future plans are still nebulous.' },
    { word: 'Obfuscate', translation: 'Ofuscar', example: 'Don\'t try to obfuscate the facts.' },
    { word: 'Pervasive', translation: 'Omnipresente', example: 'Social media is pervasive in modern life.' },
    { word: 'Quixotic', translation: 'Quijotesco', example: 'He had a quixotic vision of world peace.' },
    { word: 'Rancor', translation: 'Rencor', example: 'The two rivals spoke with rancor.' },
    { word: 'Superfluous', translation: 'Superfluo', example: 'Avoid superfluous words in your writing.' },
    { word: 'Tenuous', translation: 'Tenue', example: 'The evidence is tenuous at best.' },
    { word: 'Ubiquitous', translation: 'Ubicuidad', example: 'Smartphones are ubiquitous nowadays.' },
    { word: 'Voracious', translation: 'Voraz', example: 'He is a voracious reader.' },
    { word: 'Wistful', translation: 'Melancólico', example: 'He gave a wistful smile at the photo.' },
    { word: 'Zealous', translation: 'Ferviente', example: 'She is a zealous advocate for reform.' },
    { word: 'Abject', translation: 'Abyecto', example: 'They lived in abject poverty.' },
    { word: 'Belligerent', translation: 'Beligerante', example: 'The country took a belligerent stance.' },
    { word: 'Candid', translation: 'Cándido/Sincero', example: 'He gave a candid assessment.' },
    { word: 'Debilitate', translation: 'Debilitar', example: 'The disease can debilitate the body.' }
];

// --- GERMAN CONTENT ---
const deB1Words = [
    { word: 'Termin', translation: 'Cita', example: 'Ich habe einen Termin um 14 Uhr.' },
    { word: 'Kollege', translation: 'Colega', example: 'Mein Kollege ist sehr nett.' },
    { word: 'Besprechung', translation: 'Reunión', example: 'Die Besprechung dauert eine Stunde.' },
    { word: 'Beruf', translation: 'Profesión', example: 'Was ist dein Beruf?' },
    { word: 'Erfahrung', translation: 'Experiencia', example: 'Er hat viel Erfahrung im Job.' },
    { word: 'Gehalt', translation: 'Salario', example: 'Das Gehalt wird pünktlich gezahlt.' },
    { word: 'Vertrag', translation: 'Contrato', example: 'Unterschreiben Sie den Vertrag.' },
    { word: 'Bewerbung', translation: 'Solicitud', example: 'Ich schreibe eine Bewerbung.' },
    { word: 'Abteilung', translation: 'Departamento', example: 'In welcher Abteilung arbeitest du?' },
    { word: 'Überstunden', translation: 'Horas extras', example: 'Ich mache heute Überstunden.' },
    { word: 'Kündigung', translation: 'Renuncia/Despido', example: 'Er hat die Kündigung erhalten.' },
    { word: 'Fortbildung', translation: 'Formación continua', example: 'Ich besuche eine Fortbildung.' },
    { word: 'Leistung', translation: 'Rendimiento', example: 'Seine Leistung ist hervorragend.' },
    { word: 'Verantwortung', translation: 'Responsabilidad', example: 'Tragen Sie Verantwortung.' },
    { word: 'Zusammenarbeit', translation: 'Colaboración', example: 'Gute Zusammenarbeit ist wichtig.' }
];

const deB2Words = [
    { word: 'Nachhaltigkeit', translation: 'Sostenibilidad', example: 'Nachhaltigkeit ist ein wichtiges Thema.' },
    { word: 'Umweltschutz', translation: 'Protecc. ambiental', example: 'Umweltschutz geht uns alle an.' },
    { word: 'Klimawandel', translation: 'Cambio climático', example: 'Der Klimawandel ist sichtbar.' },
    { word: 'Erneuerbar', translation: 'Renovable', example: 'Windkraft ist erneuerbar.' },
    { word: 'Ressourcen', translation: 'Recursos', example: 'Schonen wir unsere Ressourcen.' },
    { word: 'Verschmutzung', translation: 'Contaminación', example: 'Die Meeresverschmutzung nimmt zu.' },
    { word: 'Ökosystem', translation: 'Ecosistema', example: 'Das Ökosystem ist empfindlich.' },
    { word: 'Recycling', translation: 'Reciclaje', example: 'Recycling spart Energie.' },
    { word: 'Atmosphäre', translation: 'Atmósfera', example: 'Die Atmosphäre ist dünn.' },
    { word: 'Biodiversität', translation: 'Biodiversidad', example: 'Vielfalt fördert Biodiversität.' },
    { word: 'Entwaldung', translation: 'Deforestación', example: 'Stoppt die Entwaldung.' },
    { word: 'Emissionen', translation: 'Emisiones', example: 'Wir müssen Emissionen senken.' },
    { word: 'Lebensraum', translation: 'Hábitat', example: 'Tiere brauchen ihren Lebensraum.' },
    { word: 'Schutzgebiet', translation: 'Zona protegida', example: 'Dies ist ein Naturschutzgebiet.' },
    { word: 'Verbrauch', translation: 'Consumo', example: 'Senken Sie Ihren Wasserverbrauch.' },
    { word: 'Effizienz', translation: 'Eficiencia', example: 'Energieeffizienz ist der Schlüssel.' },
    { word: 'Solarenergie', translation: 'Energía solar', example: 'Solarenergie ist sauber.' },
    { word: 'Windkraft', translation: 'Energía eólica', example: 'Windkraft wird immer wichtiger.' },
    { word: 'Ozonloch', translation: 'Agujero de ozono', example: 'Das Ozonloch wird kleiner.' },
    { word: 'Abfall', translation: 'Residuos', example: 'Vermeiden Sie unnötigen Abfall.' },
    { word: 'Entsorgung', translation: 'Eliminación (residuos)', example: 'Sichere Entsorgung ist nötig.' },
    { word: 'Gefahrgut', translation: 'Mercancía peligrosa', example: 'Vorsicht beim Transport von Gefahrgut.' },
    { word: 'Dürre', translation: 'Sequía', example: 'Die Ernte leidet unter der Dürre.' },
    { word: 'Überschwemmung', translation: 'Inundación', example: 'Es gab eine schwere Überschwemmung.' },
    { word: 'Umweltbewusstsein', translation: 'Conciencia ambiental', example: 'Stärken wir das Umweltbewusstsein.' },
    { word: 'Naturschutz', translation: 'Conservación', example: 'Naturschutz ist Bürgerpflicht.' },
    { word: 'Rohstoffe', translation: 'Materias primas', example: 'Rohstoffe sind begrenzt.' },
    { word: 'Wiederverwertung', translation: 'Reutilización', example: 'Wiederverwertung schont die Umwelt.' },
    { word: 'Giftig', translation: 'Tóxico', example: 'Diese Dämpfe sind hochgiftig.' },
    { word: 'Gleichgewicht', translation: 'Equilibrio', example: 'Das biologische Gleichgewicht.' }
];

const deC1Words = [
    { word: 'Erkenntnis', translation: 'Hallazgo/Conocimiento', example: 'Wissenschaftliche Erkenntnisse sind neu.' },
    { word: 'Voraussetzung', translation: 'Requisito', example: 'Das ist eine zwingende Voraussetzung.' },
    { word: 'Herausforderung', translation: 'Desafío', example: 'Wir stehen vor einer Herausforderung.' },
    { word: 'Verantwortung', translation: 'Responsabilidad', example: 'Tragen Sie soziale Verantwortung.' },
    { word: 'Wahrnehmung', translation: 'Percepción', example: 'Die Wahrnehmung der Welt ist subjektiv.' },
    { word: 'Zusammenhang', translation: 'Relación/Contexto', example: 'Der Zusammenhang ist komplex.' },
    { word: 'Bedeutung', translation: 'Significado', example: 'Was ist die tiefere Bedeutung?' },
    { word: 'Auswirkung', translation: 'Impacto/Efecto', example: 'Die Auswirkungen sind gravierend.' },
    { word: 'Entscheidung', translation: 'Decisión', example: 'Treffen Sie eine klare Entscheidung.' },
    { word: 'Gerechtigkeit', translation: 'Justicia', example: 'Soziale Gerechtigkeit ist ein Ziel.' },
    { word: 'Vielfalt', translation: 'Diversidad', example: 'Kulturelle Vielfalt bereichert uns.' },
    { word: 'Perspektive', translation: 'Perspectiva', example: 'Ein Wechsel der Perspektive hilft.' },
    { word: 'Interpretation', translation: 'Interpretación', example: 'Jeder hat seine eigene Interpretation.' },
    { word: 'Komplexität', translation: 'Complejidad', example: 'Die Komplexität der modernen Welt.' },
    { word: 'Nachhaltigkeit', translation: 'Sostenibilidad', example: 'Nachhaltiges Handeln ist gefragt.' },
    { word: 'Entwicklung', translation: 'Desarrollo', example: 'Die stetige Entwicklung geht weiter.' },
    { word: 'Struktur', translation: 'Estructura', example: 'Die Struktur des Textes ist logisch.' },
    { word: 'Methodik', translation: 'Metodología', example: 'Die wissenschaftliche Methodik ist streng.' },
    { word: 'Hypothese', translation: 'Hipótesis', example: 'Stellen Sie eine fundierte Hypothese auf.' },
    { word: 'Analyse', translation: 'Análisis', example: 'Die Analyse der Daten dauert an.' },
    { word: 'Kritik', translation: 'Crítica', example: 'Konstruktive Kritik ist willkommen.' },
    { word: 'Konsens', translation: 'Consenso', example: 'Wir brauchen einen gesellschaftlichen Konsens.' },
    { word: 'Differenz', translation: 'Diferencia', example: 'Beachten Sie die feinen Differenzen.' },
    { word: 'Potenzial', translation: 'Potencial', example: 'Nutzen Sie Ihr volles Potenzial.' },
    { word: 'Implementierung', translation: 'Implementación', example: 'Die Implementierung der Software.' },
    { word: 'Reflexion', translation: 'Reflexión', example: 'Selbstreflexion ist Teil des Prozesses.' },
    { word: 'Integrität', translation: 'Integridad', example: 'Handeln Sie stets mit Integrität.' },
    { word: 'Authentizität', translation: 'Autenticidad', example: 'Die Authentizität des Zeugen.' },
    { word: 'Souveränität', translation: 'Soberanía', example: 'Er bewahrt seine Souveränität.' },
    { word: 'Subjektivität', translation: 'Subjetividad', example: 'Jede Meinung hat eine Subjektivität.' },
    { word: 'Objektivität', translation: 'Objetividad', example: 'Wissenschaft erfordert Objektivitat.' },
    { word: 'Effektivität', translation: 'Efectividad', example: 'Steigern Sie die Effektivität.' },
    { word: 'Produktivität', translation: 'Productividad', example: 'Die Produktivität hat sich erhöht.' },
    { word: 'Flexibilität', translation: 'Flexibilidad', example: 'Moderne Arbeit fordert Flexibilität.' },
    { word: 'Stabilität', translation: 'Estabilidad', example: 'Wirtschaftliche Stabilität ist wichtig.' },
    { word: 'Dynamik', translation: 'Dinámica', example: 'Die Marktdynamik ändert sich.' },
    { word: 'Präzision', translation: 'Precisión', example: 'Arbeiten Sie mit höchster Präzision.' },
    { word: 'Relevanz', translation: 'Relevancia', example: 'Die Relevanz dieser Studie.' },
    { word: 'Transparenz', translation: 'Transparencia', example: 'Sorgen wir für mehr Transparenz.' },
    { word: 'Toleranz', translation: 'Tolerancia', example: 'Gegenseitige Toleranz ist die Basis.' },
    { word: 'Akzeptanz', translation: 'Aceptación', example: 'Die gesellschaftliche Akzeptanz.' },
    { word: 'Solidarität', translation: 'Solidaridad', example: 'Zeigen Sie Solidarität mit anderen.' },
    { word: 'Engagement', translation: 'Compromiso', example: 'Ihr Engagement wird geschätzt.' },
    { word: 'Kreativität', translation: 'Creatividad', example: 'Kreativität kennt keine Grenzen.' },
    { word: 'Innovation', translation: 'Innovación', example: 'Innovation treibt uns an.' }
];

export const defaultContent = {
    en: {
        B1: { topics: [{ id: 'en-b1-t1', title: 'Work', words: enB1Words }] },
        B2: { topics: [{ id: 'en-b2-t1', title: 'Environment', words: enB2Words }] },
        C1: { topics: [{ id: 'en-c1-t1', title: 'Philosophy & Ethics', words: enC1Words }] }
    },
    de: {
        B1: { topics: [{ id: 'de-b1-t1', title: 'Arbeit', words: deB1Words }] },
        B2: { topics: [{ id: 'de-b2-t1', title: 'Umwelt', words: deB2Words }] },
        C1: { topics: [{ id: 'de-c1-t1', title: 'Philosophie', words: deC1Words }] }
    }
};
